export const BOOKS_LIST_REQUEST = "BOOKS_LIST_REQUEST";
export const BOOKS_LIST_SUCCESS = "BOOKS_LIST_SUCCESS";
export const BOOKS_LIST_FAIL = "BOOKS_LIST_FAIL";

export const DELETE_BOOK_REQUEST = "DELETE_BOOK_REQUEST";
export const DELETE_BOOK_SUCCESS = "DELETE_BOOK_SUCCESS";
export const DELETE_BOOK_FAIL = "DELETE_BOOK_FAIL";

export const DELETE_ALL_BOOKS_REQUEST = "DELETE_ALL_BOOKS_REQUEST";
export const DELETE_ALL_BOOKS_SUCCESS = "DELETE_ALL_BOOKS_SUCCESS";
export const DELETE_ALL_BOOKS_FAIL = "DELETE_ALL_BOOKS_FAIL";

export const BOOK_DETAILS_REQUEST = "BOOK_DETAILS_REQUEST";
export const BOOK_DETAILS_SUCCESS = "BOOK_DETAILS_SUCCESS";
export const BOOK_DETAILS_FAIL = "BOOK_DETAILS_FAIL";
export const BOOK_DETAILS_RESET = "BOOK_DETAILS_RESET";

export const BOOK_REVIEW_REQUEST = "BOOK_REVIEW_REQUEST";
export const BOOK_REVIEW_SUCCESS = "BOOK_REVIEW_SUCCESS";
export const BOOK_REVIEW_FAIL = "BOOK_REVIEW_FAIL";
export const BOOK_REVIEW_RESET = "BOOK_REVIEW_RESET";

export const CREATE_BOOK_REQUEST = "CREATE_BOOK_REQUEST";
export const CREATE_BOOK_SUCCESS = "CREATE_BOOK_SUCCESS";
export const CREATE_BOOK_FAIL = "CREATE_BOOK_FAIL";
export const CREATE_BOOK_RESET = "CREATE_BOOK_RESET";
