export const BOOKS_LIST_REQUEST = "BOOKS_LIST_REQUEST";
export const BOOKS_LIST_SUCCESS = "BOOKS_LIST_SUCCESS";
export const BOOKS_LIST_FAIL = "BOOKS_LIST_FAIL";

export const DELETE_BOOK_REQUEST = "DELETE_BOOK_REQUEST";
export const DELETE_BOOK_SUCCESS = "DELETE_BOOK_SUCCESS";
export const DELETE_BOOK_FAIL = "DELETE_BOOK_FAIL";

export const DELETE_ALL_BOOKS_REQUEST = "DELETE_ALL_BOOKS_REQUEST";
export const DELETE_ALL_BOOKS_SUCCESS = "DELETE_ALL_BOOKS_SUCCESS";
export const DELETE_ALL_BOOKS_FAIL = "DELETE_ALL_BOOKS_FAIL";
