export const GET_ALL_EMOTIONS_REQUEST = "GET_ALL_EMOTIONS_REQUEST";
export const GET_ALL_EMOTIONS_SUCCESS = "GET_ALL_EMOTIONS_SUCCESS";
export const GET_ALL_EMOTIONS_FAIL = "GET_ALL_EMOTIONS_FAIL";

export const CREATE_EMOTIONS_REQUEST = "CREATE_EMOTIONS_REQUEST";
export const CREATE_EMOTIONS_SUCCESS = "CREATE_EMOTIONS_SUCCESS";
export const CREATE_EMOTIONS_FAIL = "CREATE_EMOTIONS_FAIL";
export const CREATE_EMOTIONS_RESET = "CREATE_EMOTIONS_RESET";

export const UPDATE_EMOTIONS_REQUEST = "UPDATE_EMOTIONS_REQUEST";
export const UPDATE_EMOTIONS_SUCCESS = "UPDATE_EMOTIONS_SUCCESS";
export const UPDATE_EMOTIONS_FAIL = "UPDATE_EMOTIONS_FAIL";
export const UPDATE_EMOTIONS_RESET = "UPDATE_EMOTIONS_RESET";

export const DELETE_EMOTIONS_REQUEST = "DELETE_EMOTIONS_REQUEST";
export const DELETE_EMOTIONS_SUCCESS = "DELETE_EMOTIONS_SUCCESS";
export const DELETE_EMOTIONS_FAIL = "DELETE_EMOTIONS_FAIL";
export const DELETE_EMOTIONS_RESET = "DELETE_EMOTIONS_RESET";
