export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGIN_RESET = "USER_LOGIN_RESET";
export const USER_LOGOUT = "USER_LOGOUT";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";
export const USER_REGISTER_RESET = "USER_REGISTER_RESET";

export const USER_UPDATA_PROFILE_REQUEST = "USER_UPDATA_PROFILE_REQUEST";
export const USER_UPDATA_PROFILE_SUCCESS = "USER_UPDATA_PROFILE_SUCCESS";
export const USER_UPDATA_PROFILE_FAIL = "USER_UPDATA_PROFILE_FAIL";
export const USER_UPDATA_PROFILE_RESET = "USER_UPDATA_PROFILE_RESET";

export const USER_DELETE_REQUEST = "USER_DELETE_REQUEST";
export const USER_DELETE_SUCCESS = "USER_DELETE_SUCCESS";
export const USER_DELETE_FAIL = "USER_DELETE_FAIL";
export const USER_DELETE_RESET = "USER_DELETE_RESET";

export const USER_CHANGE_PASSWORD_REQUEST = "USER_CHANGE_PASSWORD_REQUEST";
export const USER_CHANGE_PASSWORD_SUCCESS = "USER_CHANGE_PASSWORD_SUCCESS";
export const USER_CHANGE_PASSWORD_FAIL = "USER_CHANGE_PASSWORD_FAIL";
export const USER_CHANGE_PASSWORD_RESET = "USER_CHANGE_PASSWORD_RESET";

// FAVOURITE BOKKS CONSTANTS

export const USER_GET_LIKED_BOOKS_REQUEST = "USER_GET_LIKED_BOOKS_REQUEST";
export const USER_GET_LIKED_BOOKS_SUCCESS = "USER_GET_LIKED_BOOKS_SUCCESS";
export const USER_GET_LIKED_BOOKS_FAIL = "USER_GET_LIKED_BOOKS_FAIL";
export const USER_GET_LIKED_BOOKS_RESET = "USER_GET_LIKED_BOOKS_RESET";

export const DELETE_ALL_FAVORITES_REQUEST = "DELETE_ALL_FAVORITES_REQUEST";
export const DELETE_ALL_FAVORITES_SUCCESS = "DELETE_ALL_FAVORITES_SUCCESS";
export const DELETE_ALL_FAVORITES_FAIL = "DELETE_ALL_FAVORITES_FAIL";
export const DELETE_ALL_FAVORITES_RESET = "DELETE_ALL_FAVORITES_RESET";

export const GET_ALL_USERS_REQUEST = "GET_ALL_USERS_REQUEST";
export const GET_ALL_USERS_SUCCESS = "GET_ALL_USERS_SUCCESS";
export const GET_ALL_USERS_FAIL = "GET_ALL_USERS_FAIL";
export const GET_ALL_USERS_RESET = "GET_ALL_USERS_RESET";

export const DELETE_USER_REQUEST = "DELETE_USER_REQUEST";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAIL = "DELETE_USER_FAIL";
export const DELETE_USER_RESET = "DELETE_USER_RESET";
